### ISSUE TITLE
용돈기입장 분석

### ISSUE THREAD

**Issue by gustjr011** [itells/accountbook#1]
1. 날짜
2. 내용
3. 입출내역
4. 잔고

_1. 수입의합
_2. 지출의합
![1](https://cloud.githubusercontent.com/assets/6337285/7114795/fd656cba-e21b-11e4-83fd-0697bf55e0b7.jpg)

**Comment by gustjr011** [comment]
http://www.wikitree.co.kr/main/news_view.php?id=78216

**Comment by itells** [comment]
### 업무분석 정리1
* 일/주/월 단위 예산 편성
* 입출내역기록(날짜, 내용, 수입, 지출, 잔고)
* 수입/지출 Summary
* 입출내역 기록시 추후 트렌드 산출을 위하여 카테고리 분류 필요
